# Generated by Django 3.2.3 on 2021-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gifs',
            name='category',
            field=models.ManyToManyField(related_name='gif_category', to='gifs.Category'),
        ),
    ]
